[package]
name = "practice-rust-game"
version = "0.1.0"
authors = ["buyoh <japanjetone@live.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gio = "0.9.1"
gtk = "0.9.2"
